// TalentLens AI — Mock Data
// Realistic recruiter-focused data for enterprise AI recruiting platform

export const candidates = [
  {
    id: "c001",
    rank: 1,
    name: "Priya Sharma",
    title: "Senior ML Engineer",
    company: "DeepMind",
    location: "London, UK",
    experience: 7,
    availability: "2 weeks",
    fitScore: 96,
    technicalFit: 98,
    behavioralFit: 94,
    trustScore: 97,
    growthPotential: 92,
    semanticMatch: 95,
    skills: ["PyTorch", "Transformers", "RLHF", "Distributed Training", "Python", "CUDA"],
    tags: ["Top Match", "Hidden Talent", "High Growth"],
    summary:
      "Ex-Google Brain researcher with 7 years building large-scale ML systems. Published 3 papers on efficient transformer architectures. Demonstrates rare combination of research depth and production engineering.",
    careerTimeline: [
      { year: 2017, role: "ML Research Intern", company: "Google Brain" },
      { year: 2018, role: "Research Engineer", company: "Google Brain" },
      { year: 2021, role: "Senior Research Scientist", company: "Hugging Face" },
      { year: 2023, role: "Senior ML Engineer", company: "DeepMind" },
    ],
    behavioralSignals: {
      leadershipIndex: 78,
      collaborationScore: 91,
      adaptabilityScore: 88,
      communicationScore: 85,
      problemSolvingScore: 97,
    },
    trustSignals: {
      verifiedExperience: true,
      githubActivity: "High",
      publicationRecord: true,
      consistentCareerTrajectory: true,
      anomalyFlags: 0,
    },
    activitySignals: {
      openSourceContributions: 142,
      githubStars: 3400,
      recentJobSwitch: false,
      responseRate: 87,
      lastActive: "3 days ago",
    },
    riskIndicators: [],
    strengths: [
      "Exceptional research-to-production track record",
      "Hands-on CUDA/GPU optimization expertise",
      "Strong open source presence with 3.4K GitHub stars",
      "Published researcher with peer-reviewed work",
    ],
    weaknesses: [
      "Limited management experience",
      "Prefers IC role over leadership",
    ],
    aiExplanation:
      "Ranked #1 because semantic analysis reveals deep alignment between candidate's RLHF and distributed training expertise and the core job requirements. Behavioral signals indicate exceptional problem-solving capacity (97th percentile). Career trajectory shows consistent upward growth with zero unexplained gaps. Trust score of 97 reflects fully verified credentials with 142 open source contributions cross-referenced with GitHub activity.",
    hiringRecommendation: "Strong Hire",
    atsScore: 61,
    talentlensScore: 96,
  },
  {
    id: "c002",
    rank: 2,
    name: "Marcus Chen",
    title: "Staff Engineer",
    company: "Stripe",
    location: "San Francisco, CA",
    experience: 9,
    availability: "1 month",
    fitScore: 93,
    technicalFit: 95,
    behavioralFit: 89,
    trustScore: 94,
    growthPotential: 88,
    semanticMatch: 91,
    skills: ["Distributed Systems", "Go", "Kubernetes", "gRPC", "PostgreSQL", "Python"],
    tags: ["Senior Hire", "Infrastructure Expert"],
    summary:
      "Staff engineer with deep expertise in payment infrastructure at scale. Led migration of Stripe's core payment processing to microservices, handling 1M+ TPS.",
    careerTimeline: [
      { year: 2015, role: "Software Engineer", company: "Amazon" },
      { year: 2018, role: "Senior Engineer", company: "Lyft" },
      { year: 2020, role: "Staff Engineer", company: "Stripe" },
    ],
    behavioralSignals: {
      leadershipIndex: 89,
      collaborationScore: 86,
      adaptabilityScore: 82,
      communicationScore: 91,
      problemSolvingScore: 94,
    },
    trustSignals: {
      verifiedExperience: true,
      githubActivity: "Medium",
      publicationRecord: false,
      consistentCareerTrajectory: true,
      anomalyFlags: 0,
    },
    activitySignals: {
      openSourceContributions: 67,
      githubStars: 890,
      recentJobSwitch: false,
      responseRate: 72,
      lastActive: "1 week ago",
    },
    riskIndicators: ["Below-average open source activity"],
    strengths: [
      "Proven at extreme scale (1M+ TPS)",
      "Strong leadership track record at Stripe",
      "Deep distributed systems expertise",
    ],
    weaknesses: [
      "Limited ML/AI background",
      "Lower open source engagement",
    ],
    aiExplanation:
      "Ranked #2 due to exceptional systems engineering depth. Behavioral analysis shows strong leadership signals. Semantic match on distributed systems and infrastructure requirements is 91%. Minor gap in ML-specific experience noted.",
    hiringRecommendation: "Strong Hire",
    atsScore: 78,
    talentlensScore: 93,
  },
  {
    id: "c003",
    rank: 3,
    name: "Aisha Okonkwo",
    title: "ML Platform Engineer",
    company: "Cohere",
    location: "Toronto, CA",
    experience: 5,
    availability: "Immediate",
    fitScore: 91,
    technicalFit: 89,
    behavioralFit: 96,
    trustScore: 88,
    growthPotential: 97,
    semanticMatch: 88,
    skills: ["MLOps", "Ray", "Apache Spark", "Python", "Docker", "Terraform"],
    tags: ["Hidden Talent", "High Growth", "Immediate"],
    summary:
      "5-year ML platform engineer with exceptional behavioral signals and highest growth potential in the cohort. Self-taught background with rapid advancement at Cohere.",
    careerTimeline: [
      { year: 2019, role: "Data Engineer", company: "Shopify" },
      { year: 2021, role: "ML Engineer", company: "Cohere" },
      { year: 2023, role: "ML Platform Engineer", company: "Cohere" },
    ],
    behavioralSignals: {
      leadershipIndex: 91,
      collaborationScore: 97,
      adaptabilityScore: 95,
      communicationScore: 93,
      problemSolvingScore: 89,
    },
    trustSignals: {
      verifiedExperience: true,
      githubActivity: "High",
      publicationRecord: false,
      consistentCareerTrajectory: true,
      anomalyFlags: 0,
    },
    activitySignals: {
      openSourceContributions: 203,
      githubStars: 1200,
      recentJobSwitch: false,
      responseRate: 94,
      lastActive: "Today",
    },
    riskIndicators: [],
    strengths: [
      "Highest growth potential score in cohort (97th percentile)",
      "Exceptional behavioral signals across all dimensions",
      "203 open source contributions with active engagement",
      "Immediate availability",
    ],
    weaknesses: [
      "Less experience than top candidates",
      "No published research",
    ],
    aiExplanation:
      "Ranked #3 primarily due to exceptional growth potential and behavioral fit. Traditional ATS would rank this candidate much lower due to fewer years of experience. TalentLens semantic analysis reveals deep platform engineering expertise that directly matches requirements.",
    hiringRecommendation: "Hire",
    atsScore: 43,
    talentlensScore: 91,
  },
  {
    id: "c004",
    rank: 4,
    name: "David Hoffmann",
    title: "Principal Data Scientist",
    company: "Palantir",
    location: "New York, NY",
    experience: 11,
    availability: "3 months",
    fitScore: 87,
    technicalFit: 91,
    behavioralFit: 81,
    trustScore: 96,
    growthPotential: 74,
    semanticMatch: 84,
    skills: ["Python", "Spark", "Statistical Modeling", "SQL", "R", "Tableau"],
    tags: ["Senior Hire", "Palantir Alumni"],
    summary: "11-year veteran data scientist with Palantir pedigree. Expert in enterprise data pipelines and statistical analysis at scale.",
    careerTimeline: [
      { year: 2013, role: "Data Analyst", company: "Bloomberg" },
      { year: 2016, role: "Senior Data Scientist", company: "Palantir" },
      { year: 2021, role: "Principal Data Scientist", company: "Palantir" },
    ],
    behavioralSignals: {
      leadershipIndex: 85,
      collaborationScore: 78,
      adaptabilityScore: 72,
      communicationScore: 88,
      problemSolvingScore: 91,
    },
    trustSignals: {
      verifiedExperience: true,
      githubActivity: "Low",
      publicationRecord: false,
      consistentCareerTrajectory: true,
      anomalyFlags: 0,
    },
    activitySignals: {
      openSourceContributions: 12,
      githubStars: 45,
      recentJobSwitch: false,
      responseRate: 61,
      lastActive: "2 weeks ago",
    },
    riskIndicators: ["Long notice period", "Below-average adaptability score"],
    strengths: [
      "Elite enterprise data science pedigree",
      "Perfect trust score consistency",
      "Strong statistical modeling expertise",
    ],
    weaknesses: [
      "3-month notice period",
      "Lower adaptability signals",
      "Minimal open source presence",
    ],
    aiExplanation:
      "Ranked #4 with excellent technical credentials. Notice period and lower adaptability scores reduce urgency fit. Strong for senior individual contributor roles.",
    hiringRecommendation: "Hire",
    atsScore: 82,
    talentlensScore: 87,
  },
  {
    id: "c005",
    rank: 5,
    name: "Zara Nwosu",
    title: "AI Research Scientist",
    company: "Anthropic",
    location: "Remote (US)",
    experience: 4,
    availability: "Immediate",
    fitScore: 85,
    technicalFit: 88,
    behavioralFit: 87,
    trustScore: 83,
    growthPotential: 94,
    semanticMatch: 86,
    skills: ["Constitutional AI", "RLHF", "Python", "JAX", "Interpretability"],
    tags: ["Hidden Talent", "Research Background"],
    summary: "4-year AI safety researcher at Anthropic with deep alignment research expertise. Non-traditional path from cognitive science PhD.",
    careerTimeline: [
      { year: 2020, role: "PhD Researcher", company: "MIT (Cognitive Science)" },
      { year: 2022, role: "AI Research Intern", company: "Anthropic" },
      { year: 2023, role: "AI Research Scientist", company: "Anthropic" },
    ],
    behavioralSignals: {
      leadershipIndex: 71,
      collaborationScore: 89,
      adaptabilityScore: 94,
      communicationScore: 87,
      problemSolvingScore: 93,
    },
    trustSignals: {
      verifiedExperience: true,
      githubActivity: "Medium",
      publicationRecord: true,
      consistentCareerTrajectory: true,
      anomalyFlags: 0,
    },
    activitySignals: {
      openSourceContributions: 89,
      githubStars: 670,
      recentJobSwitch: false,
      responseRate: 91,
      lastActive: "Yesterday",
    },
    riskIndicators: [],
    strengths: [
      "Anthropic-trained alignment expertise",
      "High growth potential (94th percentile)",
      "Non-traditional PhD background adds diversity of thought",
    ],
    weaknesses: [
      "Limited industry experience (4 years)",
      "Research-focused, less production systems",
    ],
    aiExplanation:
      "Ranked #5 with exceptional growth trajectory from non-traditional background. TalentLens detected this hidden talent that ATS systems would filter out due to non-CS PhD.",
    hiringRecommendation: "Hire",
    atsScore: 38,
    talentlensScore: 85,
  },
];

export const hiddenTalentCandidates = [
  {
    id: "ht001",
    name: "Aisha Okonkwo",
    atsScore: 43,
    talentlensScore: 91,
    growthPotential: 97,
    reason: "Self-taught background; ATS filtered on degree requirement. Behavioral and semantic signals reveal exceptional capability.",
    tag: "Hidden Gem",
    delta: 48,
  },
  {
    id: "ht002",
    name: "Zara Nwosu",
    atsScore: 38,
    talentlensScore: 85,
    growthPotential: 94,
    reason: "Non-CS PhD filtered out. Cognitive science + AI safety research directly relevant to role requirements.",
    tag: "Non-Traditional",
    delta: 47,
  },
  {
    id: "ht003",
    name: "Raj Venkataraman",
    atsScore: 51,
    talentlensScore: 88,
    growthPotential: 91,
    reason: "Career gap of 14 months. Behavioral analysis shows gap was for open-source full-time contribution. GitHub activity spike confirms.",
    tag: "High Growth",
    delta: 37,
  },
  {
    id: "ht004",
    name: "Sofia Delgado",
    atsScore: 44,
    talentlensScore: 83,
    growthPotential: 89,
    reason: "Bootcamp grad filtered by ATS. Real-world production systems show more capability than traditional CS graduates in cohort.",
    tag: "Non-Traditional",
    delta: 39,
  },
  {
    id: "ht005",
    name: "James Obi",
    atsScore: 57,
    talentlensScore: 86,
    growthPotential: 85,
    reason: "Underrepresented institution. Skills semantic match is 93% despite lower keyword density in resume.",
    tag: "Hidden Gem",
    delta: 29,
  },
  {
    id: "ht006",
    name: "Lin Wei",
    atsScore: 49,
    talentlensScore: 84,
    growthPotential: 88,
    reason: "International experience not recognized. Worked on equivalent systems to FAANG at scale in Asia-Pacific market.",
    tag: "International",
    delta: 35,
  },
];

export const jobAnalysis = {
  jobTitle: "Senior ML Engineer — Foundation Models Team",
  company: "TechCorp AI",
  postedDate: "2024-01-15",
  requiredSkills: [
    { skill: "PyTorch / JAX", weight: 95, category: "Technical Core" },
    { skill: "Distributed Training", weight: 92, category: "Technical Core" },
    { skill: "Python (Advanced)", weight: 90, category: "Technical Core" },
    { skill: "RLHF / Fine-tuning", weight: 88, category: "AI/ML Specific" },
    { skill: "CUDA / GPU Optimization", weight: 82, category: "Performance" },
    { skill: "MLflow / W&B", weight: 75, category: "Tooling" },
  ],
  preferredSkills: [
    { skill: "Transformer Architecture", weight: 71, category: "Research" },
    { skill: "LLM Evaluation", weight: 68, category: "Research" },
    { skill: "Kubernetes / Ray", weight: 65, category: "Infrastructure" },
    { skill: "Technical Writing", weight: 55, category: "Communication" },
  ],
  leadershipSignals: [
    "Led cross-functional projects",
    "Mentored junior engineers",
    "Technical decision-making authority",
    "Published or presented research",
  ],
  behavioralRequirements: [
    "High adaptability in fast-moving research environments",
    "Self-directed problem solving with ambiguous requirements",
    "Strong async communication patterns",
    "Collaborative code review culture",
    "Growth mindset with continuous learning",
  ],
  experienceRequirements: {
    minimum: 5,
    preferred: 7,
    seniorityLevel: "Senior / Staff",
    domainDepth: "Deep AI/ML research + production",
  },
  aiSummary:
    "This role requires a rare combination of research-level ML expertise and production engineering capability. The behavioral signals extracted indicate the team values autonomy and async-first collaboration. Leadership signals are secondary — this is an IC-focused role despite the 'Senior' title. Candidates with non-traditional paths who demonstrate deep technical mastery via open source or publications will outperform traditional resume-match candidates.",
  radarData: [
    { category: "Technical Depth", value: 95, fullMark: 100 },
    { category: "Research Output", value: 80, fullMark: 100 },
    { category: "System Scale", value: 88, fullMark: 100 },
    { category: "Leadership", value: 60, fullMark: 100 },
    { category: "Communication", value: 72, fullMark: 100 },
    { category: "Collaboration", value: 78, fullMark: 100 },
  ],
};

export const analyticsData = {
  timeToHire: {
    current: 18,
    previous: 34,
    unit: "days",
    change: -47,
  },
  qualityScore: {
    current: 91,
    previous: 68,
    change: +34,
  },
  hiddenTalentDiscovered: {
    count: 23,
    percentage: 31,
  },
  candidatesProcessed: 1847,
  averageMatchScore: 73.4,
  hiringFunnel: [
    { stage: "JD Analyzed", count: 1847, percentage: 100 },
    { stage: "Semantic Match", count: 892, percentage: 48 },
    { stage: "Behavioral Filter", count: 412, percentage: 22 },
    { stage: "Trust Verified", count: 187, percentage: 10 },
    { stage: "Top Ranked", count: 74, percentage: 4 },
    { stage: "Shortlisted", count: 23, percentage: 1.2 },
  ],
  skillDemand: [
    { skill: "PyTorch", demand: 89 },
    { skill: "Distributed Training", demand: 76 },
    { skill: "RLHF", demand: 71 },
    { skill: "MLOps", demand: 68 },
    { skill: "CUDA", demand: 61 },
    { skill: "Kubernetes", demand: 54 },
    { skill: "Go", demand: 48 },
    { skill: "Rust", demand: 43 },
  ],
  behaviorDistribution: [
    { type: "Problem Solvers", count: 34, percentage: 46 },
    { type: "Collaborators", count: 21, percentage: 28 },
    { type: "Leaders", count: 12, percentage: 16 },
    { type: "Communicators", count: 7, percentage: 10 },
  ],
  candidateDistribution: [
    { score: "90-100", count: 23 },
    { score: "80-89", count: 41 },
    { score: "70-79", count: 89 },
    { score: "60-69", count: 134 },
    { score: "50-59", count: 201 },
    { score: "40-49", count: 287 },
    { score: "<40", count: 1072 },
  ],
};

export const explainabilityData = {
  candidateName: "Priya Sharma",
  rank: 1,
  finalScore: 96.2,
  scoringBreakdown: [
    {
      factor: "Semantic Skill Match",
      weight: 35,
      score: 95,
      contribution: 33.25,
      explanation:
        "PyTorch, RLHF, and distributed training skills show 95% semantic alignment with JD requirements — not just keyword presence but conceptual depth validated through GitHub and publication review.",
    },
    {
      factor: "Behavioral Intelligence",
      weight: 25,
      score: 94,
      contribution: 23.5,
      explanation:
        "Problem-solving score in 97th percentile. Behavioral signals extracted from GitHub commit patterns, PR review quality, and cross-team collaboration indicators show exceptional autonomy.",
    },
    {
      factor: "Career Growth Trajectory",
      weight: 20,
      score: 92,
      contribution: 18.4,
      explanation:
        "Consistent upward trajectory with no unexplained gaps. Research → Production transition at Google Brain demonstrates rare capability bridging. Each role showed expanded scope.",
    },
    {
      factor: "Trust & Verification",
      weight: 15,
      score: 97,
      contribution: 14.55,
      explanation:
        "All 7 years of experience verified. Publication record cross-referenced with Google Scholar. GitHub contributions validate claimed skills. Zero anomaly flags detected.",
    },
    {
      factor: "Hiring Probability",
      weight: 5,
      score: 87,
      contribution: 4.35,
      explanation:
        "Response rate of 87% and recent activity on professional networks. 2-week availability notice aligns with typical senior hire timelines.",
    },
  ],
  formula:
    "Final Score = (Semantic Match × 0.35) + (Behavioral × 0.25) + (Career Trajectory × 0.20) + (Trust × 0.15) + (Hiring Probability × 0.05)",
  vsAtsPrediction: {
    atsScore: 61,
    talentlensScore: 96,
    delta: 35,
    atsWouldHave: "Ranked 47th due to non-traditional PhD and keyword gaps in resume",
    talentlensInsight: "Ranked 1st based on semantic capability mapping and behavioral intelligence",
  },
  rankingComparison: [
    { candidate: "Priya Sharma", ats: 61, tl: 96, hidden: true },
    { candidate: "Marcus Chen", ats: 78, tl: 93, hidden: false },
    { candidate: "Aisha Okonkwo", ats: 43, tl: 91, hidden: true },
    { candidate: "David Hoffmann", ats: 82, tl: 87, hidden: false },
    { candidate: "Zara Nwosu", ats: 38, tl: 85, hidden: true },
  ],
};

export const navLinks = [
  { label: "Platform", href: "/dashboard" },
  { label: "Analysis", href: "/analysis" },
  { label: "Candidates", href: "/candidates" },
  { label: "Hidden Talent", href: "/hidden-talent" },
  { label: "Analytics", href: "/analytics" },
  { label: "Explainability", href: "/explainability" },
];

export const sidebarLinks = [
  { label: "Dashboard", href: "/dashboard", icon: "LayoutDashboard" },
  { label: "Job Analysis", href: "/analysis", icon: "FileSearch" },
  { label: "Candidates", href: "/candidates", icon: "Users" },
  { label: "Hidden Talent", href: "/hidden-talent", icon: "Gem" },
  { label: "Analytics", href: "/analytics", icon: "BarChart3" },
  { label: "Explainability", href: "/explainability", icon: "Brain" },
  { label: "Settings", href: "/settings", icon: "Settings" },
];
